service: aws-ddns

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-2'}
  runtime: nodejs12.x

functions:
  updateRoute:
    handler: app.update
    events:
      - http:
          path: ping
          method: get