service: aws-ddns

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  updateRoute:
    handler: app.endpoint
    events:
      - http:
          path: ping
          method: get