# Service name
service: aws-ddns

# Serverless Framework version
frameworkVersion: ">=3.39.0"

# Provider details
provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-2'}
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'route53:ChangeResourceRecordSets'
          Resource: '*'
  
# Functions declaration
functions:
  updateDNS:
    handler: app.update
    events:
      - http:
          path: ddns
          method: get