AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Dynamic DNS Service

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs24.x

Resources:
  UpdateDNSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.update
      Policies:
        - Statement:
            - Effect: Allow
              Action: route53:ChangeResourceRecordSets
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /ddns
            Method: get

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ddns"
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref UpdateDNSFunction
